### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ArvinLake** [zhhaogen/Familia-Java#1]
在初始化webpage model的时候，familia.MHSampler.java 318行报NullPointerException

原因：
	familia.TopicModel.java 68行，new HashMap<>(_vocab.size()) 不能等换为 c++的std::vector<TopicDist>(_vocab.size())
	
	webpage的vocab_info.txt和webpage_lda.model行数不一样，触发了这个bug

**Comment by zhhaogen** [comment]
已修复
